[tool.poetry]
name        = "proteus-runtime"
version     = "0.5.23"
description = ""
authors     = []
packages    = [{ include = "proteus" }]

    [tool.poetry.dependencies]
    python             = ">=3.9,<3.13"
    azure-storage-blob = "^12.14.1"
    envclasses         = "^0.3.1"
    multipart          = "^0.2.4"
    numpy              = "^1.0.0"
    parglare           = "^0.16.0"
    pycryptodome       = "^3.20.0"
    python-json-logger = "^2.0.4"
    python-slugify     = "^8.0.1"
    requests           = "^2.28.1"
    setuptools         = "^78.1.1"
    tqdm               = "^4.65.0"


    [tool.poetry.group.dev.dependencies]
    PyJWT         = "^2.4.0"
    asyncio-mqtt  = "^0.16.2"
    paho-mqtt     = "^2.1.0"
    poethepoet    = "^0.27.0"
    pytest        = "^7.2.0"
    pytest-bdd    = "^5.0.0"
    pytest-cov    = "^3.0.0"
    pytest-mock   = "^3.5.1"
    python-dotenv = "^1.0.1"
    requests-mock = "^1.8.0"

[tool.poe.tasks]
# Composing commands
test = ['pytest']

    [tool.poe.tasks.pytest]
    cmd  = "pytest tests"
    help = "Run python tests"


[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
