[project]
name = "mcp-server-email-cuhksz"
version = "0.1.3"
description = "A Model Context Protocol server for email"
readme = "README.md"
authors = [{name = "LKCY23", email = "lkcydream@gmail.com"}]
keywords = ["CUHKSZ", "MCP", "Email"]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"

# 运行时依赖
dependencies = [
    "mcp>=1.12.0",
    "fastmcp>=2.0.0",
    "python-dotenv",
    "pydantic"
]

[project.scripts]
# 安装后生成可执行脚本 'mcp-server-email-cuhksz'
mcp-server-email-cuhksz = "mcp_server_email_cuhksz.__main__:main"

# （可选）如果你用到了数据文件或额外资源
[tool.setuptools.package-data]
"mcp_server_email_cuhksz" = ["*.json", "*.yaml"]