[project]

name = "ncbi_cdonel"

version = "0.1.0"

authors = [{name = "Cory Donelson", email = "coryjdonelson@gmail.com"},]

description = "A set of tools to retrieve NCBI records."

readme = "README.md"

requires-python = ">=3.9"

dependencies = ["biopython >= 1.85"]

[project.urls]
Homepage = "https://github.com/cdonel/ncbi"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
