[project]
name = "sfu-torch-lib"
version = "0.0.59"
description = "Libraries that support the development of machine learning models in PyTorch."
requires-python = ">=3.12"
authors = [
  { name = "Anderson de Andrade", email = "anderson_de_andrade@sfu.ca" },
]

[tool.poetry]
exclude = ["tests/*"]

[tool.poetry.dependencies]
boto3 = "^1"
mlflow-skinny = "^3"
numpy = "^2"
pytorch-lightning = "*"
requests = "^2"
s3fs = "^2025"
torch = "*"
torchvision = "*"

[tool.poetry.extras]
extras = []

[tool.poetry.group.dev.dependencies]
defopt = "*"
ruff = "*"
basedpyright = "*"
pytest = "*"

[[tool.poetry.source]]
name = "private-upload"
url = "https://upload.pypi.org/legacy/"
priority = "supplemental"

[tool.ruff]
line-length = 120
unsafe-fixes = true

[tool.ruff.analyze]
preview = true

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
typeCheckingMode = "basic"

[tool.isort]
line_length = 120
multi_line_output = 9

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
