[project]
name = "st-microservice"
version = "2.5.4"
authors = [
    {name = "Robert Trad", email = "roberttrad@gmail.com"}
]
description = "Tools to build Microservice Backends"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent"
]
dependencies = [
    "aiodataloader<1",
    "ariadne==0.26.2",
    "asyncpg<1",
    "gunicorn<24",
    "httpx<1",
    "PyJWT<3",
    "pyparsing<4",
    "starlette<1",
    "uvicorn<1",
    "uvicorn-worker",
    "uvloop; sys_platform == \"linux\"",
    "websockets<16",
]

[project.optional-dependencies]
background-tasks = ["rq"]

[project.urls]
"Homepage" = "https://github.com/rouppart/ST-Microservice-Backend"

[dependency-groups]
dev = [
    "ruff",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100