[project]
name = "pyx3270"
version = "0.1.2"
description = "Uma interface comum utilizada para automações de terminais 3270 da IBM."
authors = [{name = "MatheusLPolidoro", email = "mattpolidoro4@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8,<=3.14"

dependencies = [
    "click==8.1.8",
    "colorama==0.4.6",
    "Pygments==2.19.1",
    "rich==14.0.0",
    "shellingham==1.5.4",
    "typer==0.15.3",
    "typing_extensions==4.13.2",
]

[project.scripts]
pyx3270 = "pyx3270.__main__:app"

[project.urls]
"Documentation" = "https://matheuslpolidoro.github.io/pyx3270/"
"Source Code" = "https://github.com/MatheusLPolidoro/pyx3270"
"Bug Tracker" = "https://github.com/MatheusLPolidoro/pyx3270/issues"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
fix = "ruff check . --fix"
format = "ruff format ."
test = "python -m pytest . -s -x --cov=pyx3270 -vv"
post_test = "python -m coverage html"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
    "ignore:function ham\\(\\) is deprecated:DeprecationWarning"
]

[tool.ruff.lint.per-file-ignores]
"pyx3270/x3270_commands.py" = ["PLR0904"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
pyx3270 = ["bin/**/*", "py.typed"]

[build-system]
requires = ["setuptools>=61.0,<70"]
build-backend = "setuptools.build_meta"

[tool.towncrier]
encoding = "utf-8-sig"
package = "pyx3270"
package_dir = "."
filename = "CHANGELOG.md"
directory = "chanlogs.d"
underlines = ["=", "-", "~"]
title_format = "Versão {version} ({project_date})"
issue_format = "[#{issue}](https://github.com/MatheusLPolidoro/pyx3270/issues/{issue})"

[[tool.towncrier.type]]
directory = "breaking"
name = ":warning: MUDANÇAS QUEBRADAS"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = ":zap: NOVAS FUNCIONALIDADES"
showcontent = true

[[tool.towncrier.type]]
directory = "enhancement"
name = ":rocket: OTIMIZAÇÕES"
showcontent = true

[[tool.towncrier.type]]
directory = "fix"
name = ":bug: CORREÇÕES"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecation"
name = ":wastebasket: OBSOLETOS"
showcontent = true

[[tool.towncrier.type]]
directory = "security"
name = ":shield: SEGURANÇA"
showcontent = true

[[tool.towncrier.type]]
directory = "docs"
name = ":open_file_folder: DOCUMENTAÇÃO"
showcontent = true

[[tool.towncrier.type]]
directory = "tests"
name = ":test_tube: TESTES"
showcontent = true

[[tool.towncrier.type]]
directory = "infra"
name = ":classical_building: INFRAESTRUTURA"
showcontent = true

[[tool.towncrier.type]]
directory = "chore"
name = ":broom: LIMPEZA"
showcontent = true
