[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enterprise-models"        # MUST match your PyPI project name
version = "0.1.7"                 # increment for new uploads
description = "My Django models package"
authors = [{name="Mani Kanta Kotla", email="your@email.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.0"
]

# Ensure migrations are included
[tool.setuptools.packages.find]
include = ["enterprise_models*"]

[tool.setuptools.package-data]
"enterprise_models" = ["migrations/*.py"]




