[project]
name = "tversky-neural-network-pytorch"
version = "0.0.1"
description = "Tversky Neural Network"
authors = [
    { name = "Tarek Liu", email = "liuyuwei.tarek@gmail.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
keywords = [
    'artificial intelligence',
    'deep learning',
    'tversky similarity',
    'psychologically plausible',
    'neural networks',
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    "numpy==1.26.4",
    "torch==2.1.2",
]

[project.urls]
Homepage = "https://pypi.org/project/tversky-neural-network-pytorch/"
Repository = "https://github.com/liuyuweitarek/tversky-neural-network-pytorch"

[tool.uv.build-backend]
module-root = "."
module-name = "tversky_neural_network"

[tool.uv.workspace]
members = [
    "tversky-neural-network",
    "docs/tversky_neural_network",
]

[project.optional-dependencies]
examples = []
test = [
    "pytest"
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]


[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "breathe==4.34.0",
    "bs4==0.0.1",
    "docutils==0.16",
    "exhale==0.2.3",
    "ipykernel>=6.30.1",
    "ipython==8.12.0",
    "matplotlib==3.5.3 ; python_full_version < '3.13'",
    "matplotlib==3.6.3 ; python_full_version >= '3.13'",
    "myst-nb==0.17.2",
    "myst-parser==0.18.1",
    "pytest",
    "python-etcd==0.4.5",
    "pytorch-sphinx-theme>=0.0.19",
    "sphinx==5.3.0",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-copybutton==0.5.0",
    "sphinx-design==0.4.0",
    "sphinx-sitemap==2.6.0",
    "sphinxcontrib-httpdomain>=1.8.1",
    "sphinxcontrib-katex==0.8.6",
    "sphinxcontrib-mermaid==1.0.0",
    "sphinxext-opengraph==0.9.1",
    "tensorboard==2.13.0 ; python_full_version < '3.13'",
    "tensorboard==2.18.0 ; python_full_version >= '3.13'",
    "twine>=6.1.0",
]
