app_name: FlowLLM
backend: http
thread_pool_max_workers: 128

mcp:
  transport: sse
  host: "0.0.0.0"
  port: 8001

http:
  host: "0.0.0.0"
  port: 8001

flow:
  llm_flow:
    flow_content: simple_llm_op
    stream: false

  llm_flow_stream:
    flow_content: stream_llm_op
    stream: true

  dashscope_deep_research:
    flow_content: dashscope_deep_research_op
    stream: true



op:
  bailian_web_search:
    backend: base_mcp_op
    params:
      mcp_name: tongyi_search
      tool_name: bailian_web_search
      clear_required: false

  

llm:
  default:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-instruct-2507
    params:
      temperature: 0.6

  qwen3_30b_instruct:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-instruct-2507

  qwen3_30b_thinking:
    backend: openai_compatible
    model_name: qwen3-30b-a3b-thinking-2507

embedding_model:
  default:
    backend: openai_compatible
    model_name: text-embedding-v4
    params:
      dimensions: 1024

vector_store:
  default:
    backend: elasticsearch
    embedding_model: default
#    params:
#      hosts: "http://localhost:9200"

external_mcp:
  tongyi_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"
  tongyi_web_parser:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/WebParser/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"
  bochaai_search:
    type: sse
    url: "https://dashscope.aliyuncs.com/api/v1/mcps/bochaai_search/sse"
    headers:
      Authorization: "Bearer {FLOW_BAILIAN_API_KEY}"