[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maleo-logging"
version = "0.0.17"
description = "Logging package for MaleoSuite"
authors = [
    { name = "Agra Bima Yuda", email = "agra@nexmedis.com" }
]
license = { text = "Proprietary"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-types>=0.7.0",
    "black>=25.1.0",
    "cachetools>=5.5.2",
    "certifi>=2025.8.3",
    "cfgv>=3.4.0",
    "charset-normalizer>=3.4.3",
    "click>=8.2.1",
    "distlib>=0.4.0",
    "filelock>=3.19.1",
    "google-api-core>=2.25.1",
    "google-auth>=2.40.3",
    "google-cloud-appengine-logging>=1.6.2",
    "google-cloud-audit-log>=0.3.2",
    "google-cloud-core>=2.4.3",
    "google-cloud-logging>=3.12.1",
    "googleapis-common-protos>=1.70.0",
    "grpc-google-iam-v1>=0.14.2",
    "grpcio>=1.74.0",
    "grpcio-status>=1.74.0",
    "identify>=2.6.13",
    "idna>=3.10",
    "importlib_metadata>=8.7.0",
    "maleo-enums>=0.0.7",
    "maleo-types-base>=0.0.3",
    "mypy_extensions>=1.1.0",
    "nodeenv>=1.9.1",
    "opentelemetry-api>=1.36.0",
    "packaging>=25.0",
    "pathspec>=0.12.1",
    "platformdirs>=4.4.0",
    "pre_commit>=4.3.0",
    "proto-plus>=1.26.1",
    "protobuf>=6.32.0",
    "pyasn1>=0.6.1",
    "pyasn1_modules>=0.4.2",
    "pydantic>=2.11.7",
    "pydantic_core>=2.33.2",
    "PyYAML>=6.0.2",
    "requests>=2.32.5",
    "rsa>=4.9.1",
    "typing-inspection>=0.4.1",
    "typing_extensions>=4.15.0",
    "urllib3>=2.5.0",
    "virtualenv>=20.34.0",
    "zipp>=3.23.0"
]

[tool.setuptools]
packages = ["maleo.logging"]

[tool.setuptools.package-data]
"maleo.logging" = ["*.json", "*.yaml"]

[tool.setuptools.package-dir]
"maleo.logging" = "src"
