[project]
name = "iagro-sdk"
version = "0.2.0"
description = "Pacote de códigos que serão reutilizados nnos projetos da IAgro"
authors = [
    {name = "armandoluz",email = "armandoari.288@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy (>=2.0.43,<3.0.0)",
    "sqlmodel (>=0.0.24,<0.0.25)",
    "pydantic (>=2.11.9,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
