[project]
name = "onc-toolbox"
version = "0.0.4"
description = "A toolbox for exploring Ocean Networks Canada data for the adventuring scientist."
authors = [
    {name = "Ian Black", email = "iantimothyblack@gmail.com"},
]
keywords = ['ONC']
readme = "README.md"
dependencies = [
    "bottleneck",
    "cartopy",
    "echopype",
    "gsw",
    "jupyter",
    "matplotlib",
    "onc",
    "netCDF4",
    "numpy",
    "pandas",
    "requests",
    "scipy",
    "xarray",
    "uv",
    "pytest",
    "ipykernel",
    "ipympl",
]

requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]



[project.urls]
Repository = 'https://github.com/IanTBlack/onc-toolbox'



[tool.setuptools.packages.find]
exclude = ["examples*",".github"]