[project]
name = "Ketzal"
version = "0.0.1"
description = "Experimental framework inspired by Laravel"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "HÃ©ctor", email = "danielramirezr27@gmail.com" }
]
license = { text = "MIT" }
keywords = ["framework", "web", "ketzal", "laravel-like"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "rich >= 12.0.0",
    "click >= 8.1.3",
    "watchdog >= 6.0.0",
    "python-dotenv >= 1.1.1"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
# cli
ketzal = "Ketzal.Ketzal:cli"
