[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DataRestriction"
version = "0.7.0"
authors = [
    { name = "luomeng007", email = "1502506285@qq.com" },
]
description = "A package for restricting the data type of user input"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable", # 开发状态（必填）
    "Programming Language :: Python :: 3", # Python 版本兼容性（必填）
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)", # GPLv3 # 许可证（必填）
    "Topic :: Software Development :: Libraries", # 项目类型（可选）
    "Operating System :: OS Independent", # 跨平台
]
dependencies = [
    "Numpy>=2.0.0",
]

[tool.setuptools.packages.find]
include = ["Debug", "DataRestriction"]

[project.urls]
"Homepage" = "https://gitee.com/camarolm/DataRestriction"
"Bug Tracker" = "https://gitee.com/camarolm/DataRestriction/issues"