[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mkdocs-asciidoctor-backend"
version = "0.0.11"
description = "Asciidoctor backend for MkDocs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "mkdocs>=1.6",
  "beautifulsoup4>=4.11"
]
authors = [{ name = "Aidan Reilly" }]

license = { text = "MIT" }
keywords = ["mkdocs", "asciidoctor", "plugin"]
classifiers = [
  "Framework :: MkDocs",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.entry-points."mkdocs.plugins"]
asciidoctor_backend = "asciidoctor_backend:AsciiDoctorPlugin"

[project.optional-dependencies]
dev = ["pytest>=8"]

[tool.flake8]
ignore = "E501"

[tool.setuptools]
packages = ["asciidoctor_backend"]

[tool.setuptools.package-data]
asciidoctor_backend = [
  "assets/*.css",
  "assets/*.js",
  "assets/*.rb"
]
