[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "langevaluate"
version = "0.2.4"
authors = [
  { name="JIN PARK", email="nwirandx@gmail.com" },
]
description = "LLM 기반의 자동 평가 시스템"
readme = "Readme.md"
requires-python = ">=3.8,<3.11"
license = { text = "MIT" }
keywords = ["LLM", "evaluation", "langchain", "NLP", "benchmarks"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langchain>=0.3",
    "langchain-community>=0.3", 
    "langchain-openai>=0.3",
    "langchain-anthropic>=0.3",
    "langchain-deepseek-official>=0.1",
    "langchain-google-genai>=0.1.0",
    "pandas>=2.0.0,<3.0.0",
    "datasets>=2.14.0",
    "python-dotenv>=1.0.0",
    "psycopg2-binary>=2.9.0",
    "polars>=1.21.0",
    "aiolimiter>=1.0.0",
    "rich>=13.0.0",
    "tomlkit>=0.12.0",
    "toml>=0.10.0",
    "bert-score==0.3.12",
    "spacy>=3.4.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1", 
    "pytest-cov>=4.1.0",
    "ipykernel>=6.0.0",
]


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/langevaluate"]

[project.urls]
"Homepage" = "https://github.com/JINAILAB/langmetrics"
"Bug Tracker" = "https://github.com/JINAILAB/langmetrics/issues"