[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-project-wizard"
version = "1.0.0"
authors = [
  { name="AaronTheNerd", email="bargeaaron@gmail.com" }
]
description = "A simple CLI Python project wizard"
requires-python = ">=3.10"

[project.scripts]
merlin = "python_project_wizard.main:main"

[tool.setuptools.packages.find]
exclude = ["test*"]

[tool.setuptools.package-data]
"*" = ["*.*"]