[tool.poetry]
name = "pcservices"
version = "0.1.3"
description = "Utility functions for Spark and BigQuery"
authors = ["Gang Huang <gang.huang@loblaw.ca>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=2.2.0"
pyspark = "^3.5.0"
google-cloud-storage = "^2.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
