[tool.poetry]
name = "zt-features-lib"
version = "0.1.6"
description = "A Python library with FastAPI endpoints, ready for PyPI."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ztfeatureslib"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
faker = "^25.0.0"
loguru = "^0.7.2"
pandas = "^2.2.2"
gliner = "^0.2.0"
presidio-analyzer = "^2.2.270"
aiofiles = "24.1.0"

[tool.poetry.scripts]
zt-features-lib = "ztfeatureslib.main:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
