[project]
name = "purviewer"
version = "0.3.0"
description = "Audit log analyzer for Microsoft Purview"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
packages = [{ include = "purviewer", from = "src" }]
dependencies = [
    "iplooker (>=0.4.0)",
    "numpy (>=2.3.3,<3.0.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "polykit (>=0.14.1)",
    "tabulate (>=0.9.0,<0.10.0)",
]

[tool.poetry.group.dev.dependencies]
polykit = { path = "../polykit" }
ruff = ">=0.13.0"
mypy = ">=1.18.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
purviewer = "purviewer.main:main"
