[project]
name = "rain-ai"
version = "0.1.18"
authors = [
  { name="jellyrain", email="guodongyu6@gmail.com" },
]
description = "Ai SDK Fore Rain"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "beautifulsoup4>=4.13.4",
    "cachetools>=5.5.2",
    "cloudpickle>=3.1.1",
    "httpx>=0.28.1",
    "jq>=1.9.1",
    "langchain>=0.3.25",
    "langchain-chroma>=0.2.4",
    "langchain-community>=0.3.25",
    "langchain-mcp-adapters>=0.1.7",
    "langchain-openai>=0.3.19",
    "langchain-text-splitters>=0.3.8",
    "langgraph>=0.4.8",
    "langgraph-checkpoint-sqlite>=2.0.10",
    "openpyxl>=3.1.5",
    "pymupdf>=1.26.1",
    "python-docx>=1.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
    "twine>=6.1.0",
]
