[tool.poetry]
name = "benchmax"
version = "0.1.1.dev6"
description = "Framework-Agnostic RL Environments for LLM Fine-Tuning"
authors = ["cgft.io"]
readme = "README.md"
packages = [
   { include = "benchmax" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastmcp = "~2.10.0"

skypilot = { version = "0.8.1", optional = true }

verl-cgft-fork = { version = "0.5.0.dev2", optional = true }
sglang = { version = "0.4.9", optional = true, extras = ["all"] }
verifiers = { version = "^0.1.1", optional = true, extras = ["train"]  }

openpyxl = { version = "3.1.5", optional = true }
xlwings = { version = "0.33.15", optional = true }

simple-salesforce = { version = ">=1.12.3", optional = true }
python-dateutil = { version = "~2.9.0", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[tool.poetry.extras]
# Independent feature extras
verifiers = ["verifiers"]
verl = ["verl-cgft-fork", "sglang"]

# Hosting-specific
skypilot = ["skypilot"]

# Environment-specific
excel-linux = ["openpyxl"]
excel = ["openpyxl", "xlwings"]
crm = ["simple-salesforce", "python-dateutil"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
