[project]
name = "pandalyze"
version = "0.1.2"
description = "pandalyze is a pandas analyzer that allows developers to use pandas more efficiently"
authors = [
    {name = "MoAkbarally",email = "mo.akbarally@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "pandas (>=2.3.2,<3.0.0)",
    "rich (>=14.1.0,<15.0.0)",
    "psutil (>=7.0.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "pandalyze", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
