[project]
name = "fastsyftbox"
version = "0.1.20"
description = "FastAPI + SyftBox"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: FastAPI",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "syft-event>=0.4.0",
    "syft-core>=0.2.8",  # syft-event anyway depends on syft-core (but we have a direct dep, so adding explicitly)
    "typer>=0.4.0",
    "httpx>=0.28.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "psutil>=5.9.0",          # System and process monitoring for performance tests
    "ruff>=0.0.1",            # Linter for Python
    "mypy>=0.910",            # Static type checker for Python
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
fastsyftbox = "fastsyftbox.cli:main"

[tool.hatch.build]
packages = ["fastsyftbox"]


[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I"]
lint.fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["E501"] # Allow longer lines in tests
