[project]
name = "freshrelease-mcp"
version = "1.5.8"
description = "An MCP server for Freshrelease"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.2.2.post1",
    "httpx==0.28.1",
    "mcp[cli]>=1.3.0",
    "pydantic>=2.10.6",
]

[[project.authors]]
name = "Kalidass mani"
email = "kalidass.mani@freshworks.com"

[build-system]
requires = [ "hatchling", "setuptools", "wheel"]
build-backend = "hatchling.build"

[project.scripts]
freshrelease-mcp = "freshrelease_mcp.server:main"
