mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
profile:
    store-selected: true
    tracing: false
    store-fake-ip: false
unified-delay: true
hosts:
    dnslog.cn: 47.244.138.18
    
dns:
    enable: true
    ipv6: false
    listen: '0.0.0.0:1053'
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    default-nameserver: [223.5.5.5]
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fake-ip-filter: ['*.lan', localhost.ptlogin2.qq.com, dns.msftncsi.com, '*.srv.nintendo.net', '*.stun.playstation.net', 'xbox.*.microsoft.com', '*.xboxlive.com']
    fallback: [1.1.1.1, 8.8.8.8]
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4] }
proxies:
    - { name: '57.61 GB | 150 GB', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'Traffic Reset: 20 Days Left', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'Expire Date: 2026-07-31', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨02', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨03', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16003', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨04', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16004', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨05', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16005', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨06', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16006', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨07', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16007', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨08', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16008', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨09', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16009', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kongä¸¨10', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '16010', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '17001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨02', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '17002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨03', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '17003', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨04', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '17004', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨05', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '17005', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '18001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨02', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '18002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨03', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '18003', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨04', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '18004', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨05', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '18005', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ Japanä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '19001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ Japanä¸¨02', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '19002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ Japanä¸¨03', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '19003', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ Japanä¸¨04', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '19004', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ Japanä¸¨05', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '19005', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ United Statesä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '20001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ United Statesä¸¨02', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '20002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ United Statesä¸¨03', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '20003', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ United Statesä¸¨04', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '20004', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ United Statesä¸¨05', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '20005', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡°ğŸ‡· South Koreaä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '21001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¨ğŸ‡¦ Canadaä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '22002', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: 'ğŸ‡¬ğŸ‡§ Great Britainä¸¨01', type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '23001', cipher: aes-256-gcm, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
    - { name: æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤, type: ss, server: sluy6p1tcgsltb3aup.8jh7tgvamqp.useraa.userdog.sbs, port: '10086', cipher: chacha20-ietf-poly1305, password: 16d9ced8-786e-44f4-bc2b-9253b5dba34b, udp: true }
proxy-groups:
    - { name: SSRDOG, type: select, proxies: [Auto, '57.61 GB | 150 GB', 'Traffic Reset: 20 Days Left', 'Expire Date: 2026-07-31', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨01', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨02', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨03', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨04', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨05', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨06', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨07', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨08', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨09', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨10', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨01', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨02', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨03', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨04', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨05', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨01', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨02', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨03', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨04', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨05', 'ğŸ‡¯ğŸ‡µ Japanä¸¨01', 'ğŸ‡¯ğŸ‡µ Japanä¸¨02', 'ğŸ‡¯ğŸ‡µ Japanä¸¨03', 'ğŸ‡¯ğŸ‡µ Japanä¸¨04', 'ğŸ‡¯ğŸ‡µ Japanä¸¨05', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨01', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨02', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨03', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨04', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨05', 'ğŸ‡°ğŸ‡· South Koreaä¸¨01', 'ğŸ‡¨ğŸ‡¦ Canadaä¸¨01', 'ğŸ‡¬ğŸ‡§ Great Britainä¸¨01', æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: Auto, type: fallback, proxies: ['ğŸ‡­ğŸ‡° Hong Kong', 'ğŸ‡¨ğŸ‡³ Taiwan', 'ğŸ‡¯ğŸ‡µ Japan', 'ğŸ‡°ğŸ‡· Korea', 'ğŸ‡¸ğŸ‡¬ Singapore', 'ğŸ‡ºğŸ‡¸ United States', 'ğŸ‡¨ğŸ‡¦ Canada', 'ğŸ‡¬ğŸ‡§ Great Britain', 'ğŸ‡¹ğŸ‡· Turkey', 'ğŸ‡³ğŸ‡± Netherlands', 'ğŸ‡«ğŸ‡· France', 'ğŸ‡©ğŸ‡ª Germany', 'ğŸ‡»ğŸ‡³ Vietnam', 'ğŸ‡²ğŸ‡¾ Malaysia', 'ğŸ‡¹ğŸ‡­ Thailand', 'ğŸ‡®ğŸ‡³ India', 'ğŸ‡µğŸ‡­ Philippines'], url: 'http://cp.cloudflare.com/generate_204', interval: 300 }
    - { name: 'ğŸ‡­ğŸ‡° Hong Kong', type: select, proxies: ['ğŸ‡­ğŸ‡° Hong Kongä¸¨01', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨02', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨03', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨04', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨05', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨06', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨07', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨08', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨09', 'ğŸ‡­ğŸ‡° Hong Kongä¸¨10'] }
    - { name: 'ğŸ‡¨ğŸ‡³ Taiwan', type: select, proxies: ['ğŸ‡¨ğŸ‡³ Taiwanä¸¨01', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨02', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨03', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨04', 'ğŸ‡¨ğŸ‡³ Taiwanä¸¨05'] }
    - { name: 'ğŸ‡¯ğŸ‡µ Japan', type: select, proxies: ['ğŸ‡¯ğŸ‡µ Japanä¸¨01', 'ğŸ‡¯ğŸ‡µ Japanä¸¨02', 'ğŸ‡¯ğŸ‡µ Japanä¸¨03', 'ğŸ‡¯ğŸ‡µ Japanä¸¨04', 'ğŸ‡¯ğŸ‡µ Japanä¸¨05'] }
    - { name: 'ğŸ‡°ğŸ‡· Korea', type: select, proxies: ['ğŸ‡°ğŸ‡· South Koreaä¸¨01'] }
    - { name: 'ğŸ‡¸ğŸ‡¬ Singapore', type: select, proxies: ['ğŸ‡¸ğŸ‡¬ Singaporeä¸¨01', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨02', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨03', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨04', 'ğŸ‡¸ğŸ‡¬ Singaporeä¸¨05'] }
    - { name: 'ğŸ‡¨ğŸ‡¦ Canada', type: select, proxies: ['ğŸ‡¨ğŸ‡¦ Canadaä¸¨01'] }
    - { name: 'ğŸ‡ºğŸ‡¸ United States', type: select, proxies: ['ğŸ‡ºğŸ‡¸ United Statesä¸¨01', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨02', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨03', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨04', 'ğŸ‡ºğŸ‡¸ United Statesä¸¨05'] }
    - { name: 'ğŸ‡¬ğŸ‡§ Great Britain', type: select, proxies: ['ğŸ‡¬ğŸ‡§ Great Britainä¸¨01'] }
    - { name: 'ğŸ‡¹ğŸ‡· Turkey', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡³ğŸ‡± Netherlands', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡«ğŸ‡· France', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡©ğŸ‡ª Germany', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡»ğŸ‡³ Vietnam', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡²ğŸ‡¾ Malaysia', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡¹ğŸ‡­ Thailand', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡®ğŸ‡³ India', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
    - { name: 'ğŸ‡µğŸ‡­ Philippines', type: select, proxies: [æ­¤åœ°å€å±¬æ–¼é«˜ç´šå¥—é¤] }
rule-providers:
    YouTube: { type: http, behavior: classical, url: 'https://api-gz.hosbbq.com/nus74f89st1/Y.yml', interval: 86400, path: ./ruleset/YouTube.yml }
    SteamCN: { type: http, behavior: classical, url: 'https://api-gz.hosbbq.com/nus74f89st1/SC.yml', interval: 86400, path: ./ruleset/SteamCN.yml }
    Bahamut: { type: http, behavior: classical, url: 'https://api-gz.hosbbq.com/nus74f89st1/Ba.yml', interval: 86400, path: ./ruleset/Bahamut.yml }
    DMM: { type: http, behavior: classical, url: 'https://api-gz.hosbbq.com/nus74f89st1/DM.yml', interval: 86400, path: ./ruleset/DMM.yml }
    ChinaMax: { type: http, behavior: classical, url: 'https://api-gz.hosbbq.com/nus74f89st1/C.yml', interval: 86400, path: ./ruleset/ChinaMax.yml }
rules:
    - 'DOMAIN,dog.ssrdog.com,SSRDOG'
    
    - 'DOMAIN,ic.adobe.io,REJECT'
    - 'DOMAIN,dyzt55url8.adobe.io,REJECT'
    - 'DOMAIN,gw8gfjbs05.adobe.io,REJECT'
    - 'DOMAIN,0mo5a70cqa.adobe.io,REJECT'
    - 'DOMAIN,ij0gdyrfka.adobe.io,REJECT'
    - 'DOMAIN,dxyeyf6ecy.adobe.io,REJECT'
    - 'DOMAIN,1hzopx6nz7.adobe.io,REJECT'
    - 'DOMAIN,ph0f2h2csf.adobe.io,REJECT'
    - 'DOMAIN,23ynjitwt5.adobe.io,REJECT'
    - 'DOMAIN,crs.cr.adobe.com,REJECT'
    - 'DOMAIN,www.photoshop.com,REJECT'
    - 'DOMAIN,cc-cdn.adobe.com,REJECT'
    - 'DOMAIN,photos.adobe.io,REJECT'
    - 'DOMAIN,cc-api-data.adobe.io,REJECT'
    - 'DOMAIN,lcs-cops.adobe.io,REJECT'
    - 'DOMAIN,cai-splunk-proxy.adobe.io,REJECT'
    - 'DOMAIN-KEYWORD,sjtu.edu.cn,DIRECT'
    - 'DOMAIN-KEYWORD,linkedin,SSRDOG'
    - 'DOMAIN-SUFFIX,okex.com,SSRDOG'
    - 'DOMAIN-SUFFIX,oklink.com,SSRDOG'
    - 'DOMAIN-SUFFIX,okx.com,SSRDOG'
    - 'RULE-SET,SteamCN,DIRECT'
    - 'RULE-SET,Bahamut,ğŸ‡¨ğŸ‡³ Taiwan'
    - 'RULE-SET,DMM,ğŸ‡¯ğŸ‡µ Japan'
    - 'RULE-SET,ChinaMax,DIRECT'
    - 'DOMAIN,local.adguard.org,DIRECT'
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR,203.0.113.0/24,DIRECT'
    - 'IP-CIDR,192.0.2.0/24,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'GEOIP,LAN,DIRECT'
    - 'MATCH,SSRDOG'
