[project]
name = "polaris-ai-datainsight"
version = "1.0.0"
description = "This package is Python SDK for Polaris AI DataInsight."
authors = [
    { name = "Polaris Office", email = "ai@polarisoffice.com"}
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/PolarisOfficeRnD/PolarisAIDataInsight/polaris-ai-datainsight"
homepage = "https://datainsight.polarisoffice.com/"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
requests = ">=2.27"
pydantic = ">=2"
python-dotenv = ">=1.1.1,<2.0.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.codespell]
optional = true

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
pytest-socket = "^0.7.0"
pytest-watcher = "^0.3.4"
langchain-tests = "^0.3.5"

[tool.poetry.group.codespell.dependencies]
codespell = "^2.2.6"

[tool.poetry.group.lint.dependencies]
ruff = "^0.5"

[tool.poetry.group.typing.dependencies]
mypy = "^1.10"
