[project]
name = "datav-twinfabric-mcp"
version = "1.4.0"
description = "DataV.TwinFabric MCP Server: A server for DataV.TwinFabric integration via the Model Context Protocol (MCP)."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "橙唯", email = "chenchengju.ccj@alibaba-inc.com" }
]
dependencies = [
  "mcp[cli]>=1.4.1",
  "fastmcp>=0.2.0",
  "uvicorn",
  "fastapi",
  "pydantic>=2.6.1",
  "dashscope",
  "requests"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.hatch.build]
include = ["datav_twinfabric_mcp/*.py"]
[project.scripts]
datav-twinfabric-mcp = "datav_twinfabric_mcp.twinfabric_mcp_server:run"
