[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AdvancedCipherLib"
version = "1.0.0"
description = "Advanced encryption and decryption library with multiple cipher algorithms"
authors = [
    { name="Naser Hnysh", email="naserhnysh@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["advancedcipher*"]

[project.urls]
"Homepage" = "https://pypi.org/"
