[project]
name = "xuri-rpc"
version = "0.1.2"
description = "xuri-rpc in python"
authors = [
    {name = "prometheus-0017"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typeguard (>=4.4.4,<5.0.0)"
]
packages = [ { include = "xuri_rpc" } ] # 指定要包含的 Python 包目录

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
